sudo: required
language: php
php:
  - "5.6"
  - "7.0"

cache:
  directories:
    - vendor

before_script:
  - composer install
  - sudo chown :travis dev/tests/integration/src/data/stego
  - sudo chmod g+rw dev/tests/integration/src/data/stego

script:
  - mkdir -p build/logs
  - phpunit -c dev/tests/phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
